### ISSUE TITLE
Problem individual mask extraction in registration.FMRISession

### ISSUE THREAD

**Issue by garincle** [sammba-mri/sammba-mri#145]
![capture2](https://user-images.githubusercontent.com/33903508/47995289-16dd2080-e0f5-11e8-8d10-c09c977fc9d5.JPG)

Hi, 
i wanted to submit this problem concerning morpho mask creation using registration.FMRISession
RATS has succeded to extract the brain on 18 rats but fail for 2 rats, including the extrenal part of the brain and exluding the brain.

brainsize = 1800
Any idea of who to fix this bug ? 
I already try to increase the brain size to 2000 ==> doesn't work
I will try the opposite ex: 1600
and without rats

i let you know,

tks 
Clément

**Comment by garincle** [comment]
without rats ==> doesn't work
decreasing the brain size to 1700 ==>  work for all and is probably more adapted to rats
tks

**Comment by salma1601** [comment]
Here are some hints, please give me the exact function you are using for brain extraction so that I can be more precise.
- Prior to brain extraction, there is an intensity unifization step that has a clipping fraction parameter. This parameter can be tuned (from .1 to .9) so that the unifization is more or less strong
- The intensity unifization can even be skipped. Sometimes this gives better results
- There is another masking strategy using the histogram thresholding.
- The default brain size for rats in RATS tool is 1650, so this value may be preferred I think
