### ISSUE TITLE
better exposure of brain extraction step

### ISSUE THREAD

**Issue by salma1601** [sammba-mri/sammba-mri#77]
Brain extraction is a very critical step in all pipelines. It also needs a lot of manual tuning, and it is not practical to launch the entire pipeline each time to find the best values for `clfrac` and other parameters. I suggest to expose a function `compute_brain_mask` and to remove brain extraction from all the pipelines, calling explicitly for brain mask files. For instance `anats_to_common` will be take `head_filenames` and `brain_filenames` as parameters.
Another problem has been raised by @mdhenain : post-mortem data there is no need for brain extraction.
@nadkarni-na do you think the registration can succeed without the head files ?

**Comment by nadkarni-na** [comment]
The brain extraction step is done at the start of the entire pipeline, and is relatively quick, so if it has gone wrong, the user will know quickly if they decide to browse the initial datasets.

To make this more explicit, rather than removing brain extraction from the pipelines, it would be better to add a fourth option to the registration_kind flag of masking_only

The registration should work even if the head files are in reality just brains.

**Comment by salma1601** [comment]
>The brain extraction step is done at the start of the entire pipeline, and is relatively quick, so if it has gone wrong, the user will know quickly if they decide to browse the initial datasets

This is not well suited to parameter tuning.

>To make this more explicit, rather than removing brain extraction from the pipelines, it would be better to add a fourth option to the registration_kind flag of masking_only

-1 for this. The number of options is exploding and it would be interesting at some point to decrease them, not to make them more complex. The masking option `brain_masking_unifize_kwargs` is itself very complex. It is difficult to understand its impact.

>The registration should work even if the head files are in reality just brains.

Ok ! great.

**Comment by nadkarni-na** [comment]
> This is not well suited to parameter tuning.
It's the only way to do parameter tuning, and is perfectly suited: the parameters are tested on all input data.

> -1 for this. The number of options is exploding and it would be interesting at some point to decrease them, not to make them more complex. The masking option brain_masking_unifize_kwargs is itself very complex. It is difficult to understand its impact.

The number of options is only a bit higher than the original shell, and has been stable for a while. Template making is inherently complex, there is no way to make it simple given the variety of input data.

Given that, aside from #78, this code works well on the very wide variety of data we have tested, this should not be a priority. There are large amounts of missing functionality (morphological measurements, perfusion calculations etc...) that are far more important

**Comment by salma1601** [comment]
>It's the only way to do parameter tuning, and is perfectly suited: the parameters are tested on all input data.

No. When I want to do parameters tuning for a failed brain mask, I want to change clfrac and **immediately** see the brain extracted result. I want one function that does just this, for one single file: 
one parameter value -> check output
I don't want to wait for an entire pipeline (whatever its length is) to crash

>this code works well on the very wide variety of data we have tested, this should not be a priority.

No it doesn't work well. I say it works well when for 80% of the data it works right with the default options.
At each time I tried it with new data (apart from Clément's sequences), it required tuning of `clfrac` or whatever.
All old data tried by @mdhenain failed, and so was Pauline's. We changed the code for Pauline's, so I don't say that it works. I say it requires parameter tuning for brain mask before it works.

>There are large amounts of missing functionality (morphological measurements, perfusion calculations etc...) that are far more important

PRs are welcome !

**Comment by mdhenain** [comment]
Being able to better expose the extraction step sounds a good idea. This will allow to explain what is the role of the various options and will facilitate the resolution of most of the problems that seem to be coming from this step.

**Comment by nadkarni-na** [comment]
> No. When I want to do parameters tuning for a failed brain mask, I want to change clfrac and immediately see the brain extracted result. I want one function that does just this, for one single file:
one parameter value -> check output

I cannot emphasise enough that this is not useful for template generation with the quality of input data we have. A good extraction on one animal is no guarantee that it will work on any others. If the parameters do not work on all the animals, and have to be changed from one animal to another, there is no point continuing as the template will no longer be treating each image identically. They have to be tested on all of them right from the start. In any case, the function for testing on an individual animal basis already exists: the user is free to access the nipype interfaces, or do testing in bash. For immediate results, the images are produced in real-time for opening. The only thing that is more immediate is piping to a GUI, which is a very large enhancement.

> At each time I tried it with new data (apart from Clément's sequences), it required tuning of clfrac or whatever.

This is inherent to the variability of SNR, CNR and contrast among studies, and even among animals within a study. There is no way around this. We are not working with human data where acquisition standards have been more stable and of higher quality for the past 20 years than they are even today in animals. And even despite that, scripts for generalized template generation in humans are 1000+ lines long.

> All old data tried by @mdhenain failed, and so was Pauline's. We changed the code for Pauline's, so I don't say that it works. I say it requires parameter tuning for brain mask before it works.

It works on @mdhenain data (according to his email to me this morning), and works for Pauline's now (the kind if the mix of non-brain tissue, poor SNR and image contrast she had had not yet been tested so it's not surprising it failed without the clfrac option that did not exist at the time because there was not yet any need for it). Of course clfrac has to be adjusted, but as explained above this is to be expected.

As I dais earlier, this can all be solved by adding a fourth option to the registration_kind flag of masking_only.

**Comment by salma1601** [comment]
Closing, as #101 gives the user the choice to input its own mask and also has a `report_brain_extraction` function useful to compare different clipping fraction values
