### ISSUE TITLE
unnecessary redoing of anat-->template in cases of multiple functionals and potentially multiple modalties

### ISSUE THREAD

**Issue by garincle** [sammba-mri/sammba-mri#94]
If their is more than 2 func images
 anat to template is made again ==> loss of time
and 
the analysis can't continu because 
output dataset name 'warped_3_adjusted_mean_resample.nii.gz' conflicts with existing file

**Comment by salma1601** [comment]
Could you please explain what function you are using and the context ? are you talking about template creation or fMRI session registration to template ?

**Comment by nadkarni-na** [comment]
when using registration.fmri_sessions_to_template, if there is more than one functional dataset, the anat-->template step us needlessly repeated, and even worse it creates outputs with the same names as the first time it was run, creating a file conflict error and quitting the program

**Comment by nadkarni-na** [comment]
another way to put this is that registration.FMRISession does not appear to accept more than one functional

**Comment by salma1601** [comment]
I am not sure to understand. It is not supposed to have one functional and one anatomical per animal ?

**Comment by nadkarni-na** [comment]
no. we frequently have more than one functional per anatomical

**Comment by salma1601** [comment]
you can set `caching=True` in `registration.fmri_sessions_to_template` function. This allows to not repeat any preprocessing step that has already been done.

**Comment by salma1601** [comment]
> 'warped_3_adjusted_mean_resample.nii.gz' 

Could you please give me the exact name of the template file and the entire name of the conflicting file?

**Comment by nadkarni-na** [comment]
@garincle was running a script where registration.fmri_sessions_to_template was within a loop where it was fed a new functional per loop cycle, but with the anat staying the same, and all data being saved to the same folder. this goes wrong as the anat from a previous loop has to be overwritten. a workaround would be to rearrange the loop in our script to save each functional to a new folder. but this is not a good solution in the long-term as it involves the anat-->template being repeated.

**Comment by salma1601** [comment]
If the original names of the files are the same (I suspect it is the case with anat_n0 and rs_n0 etc), then the preprocessed filenames will have the same name. It is something standard to use prefixing/suffixing the original filenames for naming the preprocessed files. Redirecting to different output folders seems the most logical solution.

May be in the long-term we can rethink the design of the FMRISession object if this case of figure (many funcs, one anat) is frequent use.

**Comment by nadkarni-na** [comment]
more than half of our data involves multiple functionals per anatomical. anat-->template is frequently the longest step in a spatial normalisation (in this case for @garincle, 7mins, whereas the func-->anat was only 3mins). doing the anat-->template only once was a basic feature of the bash scripts. if registration.FMRISession cannot be made to accept more than one functional, a lot of our processing will take 2-3 times longer than it did before

**Comment by nadkarni-na** [comment]
actually the problem would be horrible for certain experiments. I have mouse data where there are five "functionals": three perfusion images, a resting state and a dti. if the registration.FMRISession system is used for them, anat-->template would end up being repeated five times! and even if multiple functionals would be fed to registration.FMRISession, anat-->template would still end up being repeated for each modality

**Comment by nadkarni-na** [comment]
**Summary**

@garincle was using a bad script that misused registration.fmri_sessions_to_template in a use case where for a single session, there was a single anatomical but more than one functional. the current correct use involves creating a registration.FMRISession object for each functional and passing a list of all of these objects to the same registration.fmri_sessions_to_template call. but if I am reading func.py correctly, this necessarily involves anat--template being repeated for each registration.FMRISession object even if the anatomical paths are the same in each, which is very wasteful given that anat-->template is usually the most computationally heavy part of session processing.

even if the above problem could be solved, because the perfusion and dti registration functions are envisaged to be completely separate, anat-->template would still end up being needlessly repeated per modality

so the design of the registration system needs to be rethought to have the same performance as the bash scripts: only doing the anat-->template once.

**Comment by nadkarni-na** [comment]
actually if I read func.py correctly, even the "correct" use of registration.fmri_sessions_to_template won't work with multiple registration.FMRISession objects having the same anat name, as these would create name clashes. so in fact we have to stick to a single registration.FMRISession object per registration.fmri_sessions_to_template call, and a new write_dir per functional?

**Comment by salma1601** [comment]
Fixed in #101
